services:
  - type: web
    name: clipdrop
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
